### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#114]
The [Documentation](https://www.chesslablab.com/documentation/) shouldn't be published from the [chesslablab/website](https://github.com/chesslablab/website) repo but from the [chesslablab/chess-server](https://github.com/chesslablab/chess-server) repo using [Read the Docs](https://readthedocs.org/). This issue is a copy and paste process, a really good first issue to get familiar with the codebase.

See:

- [Write documentation](https://github.com/chesslablab/chess-api/issues/49)

Keep it up, and happy learning!

**Comment by rmknan** [comment]
I want to help with this. This will be my first contribution, Based on my understanding from the above comment I am supposed to use the [Docs](https://readthedocs.org/) to publish the documentation from this URL (https://www.chesslablab.com/documentation/) in the chesslabserver repo. Is that correct? 

Could you also provide additional details or links to help me do this?

Thank you.

**Comment by programarivm** [comment]
@rmknan welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/chess-server/blob/master/CONTRIBUTING.md).

This issue consists in the exact same copy and paste process used to create the [Chess API for Web Apps](https://chess-api.readthedocs.io/en/latest/) docs. The following commit describes the steps involved in preparing the Chess API docs for [Read the Docs](https://readthedocs.org/).

- [Issue/49 write documentation #50](https://github.com/chesslablab/chess-api/pull/50) 

Read the Docs requires two configuration files:

- readthedocs.yaml
- mkdocs.yml

Then, you're set up to start writing Markdown files in the docs folder!

Here's the original documentation that needs to be copied from the chesslablab/website repo and pasted into the chesslablab/chess-server/docs folder:

- [public/documentation/index.html](https://github.com/chesslablab/website/blob/master/public/documentation/index.html)

The following `mkdocs.yml` may well be okay to describe the content.

```text
site_name: Chess Server
pages:
  - Chess Server for Web Apps: index.md
  - /start: start.md
  - /legal_sqs: legal-sqs.md
  - /play_lan: play-lan.md
  - /undo: undo.md
  - /heuristics: heuristics.md
  - /heuristics_bar: heuristics-bar.md
theme: readthedocs
```

The thing is, probably it's not a good idea to publish technical content on chesslablab.com which is a chess website intended to chess players.

Keep it up, and happy coding and learning!

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding!

**Comment by SmashedFrenzy16** [comment]
@programarivm, here is the PR to solve this issue: https://github.com/chesslablab/chess-server/pull/116

**Comment by programarivm** [comment]
Thank you @SmashedFrenzy16, @CodeMaster7000 and @rmknan for the contributions!

Let me self-assigned this issue.

@CodeMaster7000 and @rmknan may want to check out the following one instead:

- https://github.com/chesslablab/chess-api/issues/54

Keep it up,
