### ISSUE TITLE
Use an .env variable for the allowed websites

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#135]
`www.chesslablab.com` is being hardcoded in [chess-server/cli/wss-server.php](https://github.com/chesslablab/chess-server/blob/master/cli/wss-server.php), however, an `.env` variable should be used instead.

Keep it up,

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding!

**Comment by SmashedFrenzy16** [comment]
I havemade a PR to fix this issue here: https://github.com/chesslablab/chess-server/pull/142
