### ISSUE TITLE
Write a unit test to check the /start command

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#140]
Write a unit test in [tests/unit/CommandParserTest.php](https://github.com/chesslablab/chess-server/blob/master/tests/unit/CommandParserTest.php) called `validate_start_classical_foobar()` to check that the following command doesn't pass the parser validation.

```
/start classical foobar
```

Happy coding!

**Comment by CodeMaster7000** [comment]
Hi there, happy learning and coding!
