### ISSUE TITLE
Document the /restart command

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#150]
Document the `/restart` command with examples.

Keep it up,

**Comment by mihaescuvlad** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
@mihaescuvlad welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/chess-server/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
