### ISSUE TITLE
Document the /stockfish command

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#170]
Document the `/stockfish` command with examples.

Happy learning!

**Comment by CodeMaster7000** [comment]
@programarivm Hi there, happy learning and coding!

Could you please explain what exactly I should do? I have not attempted these types of issues before.

Thanks!

**Comment by programarivm** [comment]
It is a two step process:

1. Add a new entry in the [mkdocs.yml](https://github.com/chesslablab/chess-server/blob/master/mkdocs.yml) file
2. Write the corresponding documentation file in the [docs](https://github.com/chesslablab/chess-server/tree/master/docs) folder

Then, the docs will be built using [Read the Docs](https://about.readthedocs.com/?ref=readthedocs.com).

In order to write an example into the `stockfish.md` file, you may want to look at Google Chrome developer tools.

![figure_01](https://github.com/chesslablab/chess-server/assets/4062000/9264f192-7f03-4582-bdeb-fa2c7099973d)
**Figure 1**. Click on **Play > Play Computer** and then click on **Create Game**

![figure_02](https://github.com/chesslablab/chess-server/assets/4062000/b63951a2-af09-4261-91d2-24c22bdf28b4)
**Figure 2**. Copy Stockfish's response into the `stockfish.md` file.

Also recently a TCP socket server has been implemented in the [chesslablab/chess-server](https://github.com/chesslablab/chess-server) repo for testing purposes.

![figure_03](https://github.com/chesslablab/chess-server/assets/4062000/c247b337-0210-4427-8ad5-52a35ca8f82e)
**Figure 3**. Run the cli/testing.php script.

![figure_04](https://github.com/chesslablab/chess-server/assets/4062000/6bbad4a1-2046-45f5-8101-fcf70efc6186)
**Figure 4**. Connect to the TCP server via telnet and run commands.

I hope this helps.

Happy learning!

**Comment by CodeMaster7000** [comment]
@programarivm Can you unassign me please? I may not be working on this issue and I would want others to not work on it because of me.
