### ISSUE TITLE
Document the /stockfish_eval command

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#171]
Document the `/stockfish_eval` command with examples.

Keep it up,

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
Thank you @SmashedFrenzy16 for contributing to this repo!

The examples cannot longer be obtained from chesslablab.com because the website is no longer available, so you may want to either run the app on your localhost or run the TCP socket to test [StockfishEvalCommand.php](https://github.com/chesslablab/chess-server/blob/master/src/Command/StockfishEvalCommand.php).

Let me point out the following:

- A FEN string needs to be passed to the `/stockfish_eval` command rather than a SAN movetext.

![stockfish_eval](https://github.com/chesslablab/chess-server/assets/4062000/d9a5da0c-db81-4425-a092-cf57aacd1ddf)

Happy coding and learning!
