### ISSUE TITLE
Write documentation for each command

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#172]
The following commands need to be documented with examples:

- [x] https://github.com/chesslablab/chess-server/issues/147
- [x] https://github.com/chesslablab/chess-server/issues/148
- [x] https://github.com/chesslablab/chess-server/issues/149
- [x] https://github.com/chesslablab/chess-server/issues/167
- [x] https://github.com/chesslablab/chess-server/issues/168
- [x] https://github.com/chesslablab/chess-server/issues/169
- [x] https://github.com/chesslablab/chess-server/issues/170
- [x] https://github.com/chesslablab/chess-server/issues/171
- [x] https://github.com/chesslablab/chess-server/issues/217
- [x] https://github.com/chesslablab/chess-server/issues/218

Documenting a command is a two step process.

1. Add a new entry in the [mkdocs.yml](https://github.com/chesslablab/chess-server/blob/master/mkdocs.yml) file
2. Write the corresponding documentation file in the [docs](https://github.com/chesslablab/chess-server/tree/master/docs) folder

The docs will be built using [Read the Docs](https://about.readthedocs.com/).

---

The examples can be obtained while interacting with the [www.chesslablab.com](https://www.chesslablab.com/) website as described next.

![figure_01](https://github.com/chesslablab/chess-server/assets/4062000/9264f192-7f03-4582-bdeb-fa2c7099973d)
**Figure 1**. Open Google Chrome developer tools. Click on **Play > Play Computer** and click on **Create Game** for command examples.

![figure_02](https://github.com/chesslablab/chess-server/assets/4062000/b63951a2-af09-4261-91d2-24c22bdf28b4)
**Figure 2**. As chess moves are played, Stockfish's response is displayed on the **Network > WS > Messages** tab.

Also recently a TCP socket server has been implemented in the [chesslablab/chess-server](https://github.com/chesslablab/chess-server) repo for testing purposes.

![figure_03](https://github.com/chesslablab/chess-server/assets/4062000/80207c0b-a771-4551-ad2d-616774ce30e7)
**Figure 3**. Run the `cli/testing.php` script.

![figure_04](https://github.com/chesslablab/chess-server/assets/4062000/6bbad4a1-2046-45f5-8101-fcf70efc6186)
**Figure 4**. Connect to the TCP server via telnet and run commands.

Happy learning!

**Comment by stepperpig** [comment]
Is this issue still being worked on? I'd be interested in helping write documentation and/or editing the existing ones. Let me know!

**Comment by programarivm** [comment]
@stepperpig welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/chess-server/blob/master/CONTRIBUTING.md). This is a collection of issues, please comment on a specific task so that it can be assigned to you.

Happy coding and learning,
