### ISSUE TITLE
Remove the chess games from the log

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#272]
After some beta testing it's been somewhat confirmed that the chess server is working as expected. So now there is no need to store the games in the `storage/pchess.log` file anymore for debugging purposes. 

The following files are to be updated accordingly:

- [src/Socket/RatchetClientStorage.php](https://github.com/chesslablab/chess-server/blob/main/src/Socket/WorkermanClientStorage.php)
- [src/Socket/WorkermanClientStorage.php](https://github.com/chesslablab/chess-server/blob/main/src/Socket/WorkermanClientStorage.php)

Happy coding!

**Comment by KartikWatts** [comment]
Hi there, happy learning and coding!
Kindly, assign me, would love to contribute. Regards.

**Comment by KartikWatts** [comment]
@programarivm Hi, I Raised the PR, though I just wanted to clarify something related to storing the games. Considering that the `sendToMany` and `sendToOne` methods are being called by many commands, do we want to stop storing logs only for prominent commands like: `/play_lan` which as per my analysis stores the `fen` data, so technically does this command mean *chess games* in the Issue description, or other commands like  `/stockfish`, `/online_games`, etc logs be also stopped.
However, my original idea based on analysis was to only stop logs for certain commands like  `/play_lan` which can be conditionally received from `$res`. but for the sake of simplicity, for now, stopping logs for all commands.

I will update the PR based on further clarification regarding the same. Regards.

So should we stop

**Comment by programarivm** [comment]
@KartikWatts the deleted comment has been copied and pasted into the PR.

Happy coding and learning!
