### ISSUE TITLE
WebSocketization of the API endpoints

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#311]
The API endpoints in the [chesslablab/chess-api](https://github.com/chesslablab/chess-api) repo are to be rewritten in the [chesslablab/chess-server](https://github.com/chesslablab/chess-server) in the form of WebSocket commands. One of the main reasons behind this decision is the optimization of resources. The PHP Chess API has demonstrated to be not too efficient while hosted in an AWS t2.micro instance along with [Chess Data](https://github.com/chesslablab/chess-data).

```
docker ps -a
CONTAINER ID   IMAGE            COMMAND                  CREATED        STATUS          PORTS                                                  NAMES
abb9dfb42450   chess-api-php    "docker-php-entrypoi…"   11 hours ago   Up 51 seconds   9000/tcp                                               chess_api_php
b51c5fd6b63c   nginx:1.20       "/docker-entrypoint.…"   11 hours ago   Up 51 seconds   80/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp      chess_api_nginx
034c5c242a03   mysql:8.4        "docker-entrypoint.s…"   25 hours ago   Up 51 seconds   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   chess_data_mysql
0580c1de47ba   chess-data-php   "docker-php-entrypoi…"   25 hours ago   Up 51 seconds   9000/tcp                                               chess_data_php
```

This is too many Docker containers. So we're moving to a WebSocket architecture based on multiple connections as described at [Multiple websocket connection vs single websocket connection when using django channels](https://groups.google.com/g/django-users/c/ikq9Y1H8ceA).

> Suppose an application has features like Chat, Notification and Activity feeds.

Let's stick with separation of concerns. 

- async.chesslablab.org:9443
- async.chesslablab.org:8443

The former will specialize in database commands and the latter in game commands.

See:

- [Is Workerman appropriate for database queries?](https://github.com/walkor/workerman/discussions/1045)

Happy learning!

---
- [x] https://github.com/chesslablab/chess-server/issues/321
- [x] https://github.com/chesslablab/chess-server/issues/312
- [x] https://github.com/chesslablab/chess-server/issues/313
- [x] https://github.com/chesslablab/chess-server/issues/314
- [x] https://github.com/chesslablab/chess-server/issues/315
- [x] https://github.com/chesslablab/chess-server/issues/316
- [x] https://github.com/chesslablab/chess-server/issues/317
- [x] https://github.com/chesslablab/chess-server/issues/318
- [x] https://github.com/chesslablab/chess-server/issues/319
- [x] https://github.com/chesslablab/chess-server/issues/320

**Comment by joanhey** [comment]
Please, could you show the output of `docker stats`, it's more informative about the server usage.

Another option is use SSE instead of Websockets.
Websocket it's ideal for a multiplayer shooting game, the browser could be continuously streaming the player’s position, while simultaneously receiving updates on the location of all the other players from the server

But with a chess game it is not necessary.

The Server Send Events (SSE) protocol is very simple.

**Comment by joanhey** [comment]
In reality Websockets are more vulnerable and heavier on resources.
WebSocket connections are not protected by the same-origin policy. This makes them vulnerable to Cross-Site WebSocket Hijacking.

Other drawbacks:
* No support for compression
* No support for HTTP/2 multiplexing
* Potential issues with proxies
* No protection from Cross-Site Hijacking
* etc

**Comment by joanhey** [comment]
Of course, SSE is a realtime push protocol, that stream the data continuously.
I don't know witch server app you used for the SSE.

**Comment by joanhey** [comment]
You can also use multiple SSE backends.

**Comment by joanhey** [comment]
Ratchet use ReactPHP, and ReactPHP have SSE  https://github.com/clue/php-sse-react

Workerman SSE  https://manual.workerman.net/doc/en/http/SSE.html

I did'n find the SSE protocol in AMPHP, but it's very simple to implement.

And apart from PHP, we can use any SSE server from any language transparently from PHP.

**Comment by joanhey** [comment]
I created the Workerman vmstats using SSE instead of Websockets, and the code in the backend and more in the frontend is simplified and with lees lines.

### Websockets
https://github.com/walkor/workerman-vmstat
### SSE
https://github.com/joanhey/workerman-vmstat

**Comment by joanhey** [comment]
> Suppose an application has features like Chat, Notification and Activity feeds.

SSE is the best option for that situations.

**Comment by joanhey** [comment]
I only give another option, that can simplify the code work.
But the decision is of @programarivm .

**Comment by joanhey** [comment]
Also the SSE option is very good to other people watch the games from other people.

**Comment by joanhey** [comment]
SSE was not used, because IE and Edge didn't support it till 2020, ten years later than the others browsers. 
Even when exist pollyfills for this easy protocol.

Another problem was that with http 1.1, the browsers limit to 6 connections to the same server. But now with http 2 and http3 is not a problem.

Websocket don't work with http2, use http1 and for any tab open need a new TCP connection to the server.
Exist an RFC to use webscocket with http2, but I doubt that arrive to the browsers, because for http3 exist a new protocol  WebTransport, that is better.
https://caniuse.com/?search=webtransport

**Comment by joanhey** [comment]
You can inspect all the traffic, and I think that it is OK that is readable.

![image](https://github.com/user-attachments/assets/96050588-7068-42dd-9807-a4409f4ff4f2)

**Comment by joanhey** [comment]
They send the info in binary format, that it isn't necessary for that app.
Only extra work in server and client.
![image](https://github.com/user-attachments/assets/34e07f64-3130-417b-870d-b3924ac9bafe)

**Comment by joanhey** [comment]
SSE only permit UTF8 text, for send binary they use base64-encoding.

**Comment by joanhey** [comment]
Extra work without advantages.
It's the server who need to authorize the premium features by user.

**Comment by joanhey** [comment]
Sorry I'm not here for Chessbase_com. And this issue is not also.
If you ask for my services, you need to pay me first.
Thank you.
