### ISSUE TITLE
Add a command to fetch the events happening in the game

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#32]
This issue is intended to practice software architecture skills as well as unit testing.

As you may have noted, there's a one-to-one correspondence between the `Chess\Game` methods described in the [PHP Chess docs](https://php-chess.readthedocs.io/en/latest/game-methods/) and the [commands available](https://github.com/chesslab/chess-server/tree/master/src/Command) in the chess server:

- `ascii(): string` <-> `ChessServer\Command\AsciiCommand.php`
- `captures(): array` <-> `ChessServer\Command\CapturesCommand.php`
- `castling(): ?array` <-> `ChessServer\Command\CastlingCommand.php`
- ...

However, the `ChessServer\Command\EventsCommand.php` is missing.

The missing file should be added. Also, the corresponding unit test should be written in the [`tests/unit/Command`](https://github.com/chesslab/chess-server/tree/master/tests/unit/Command) folder as per the existing conventions.

Happy learning and coding!

**Comment by Pen-y-Fan** [comment]
I'm happy to take a look at this.

**Comment by Pen-y-Fan** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/chess-server/pull/48
