### ISSUE TITLE
Db::getInstance is not correct

### ISSUE THREAD

**Issue by joanhey** [chesslablab/chess-server#352]
Only work with the first config.

If we need another db config, return the same instance from the first config.

**Comment by programarivm** [comment]
Not too sure if this is to do with https://github.com/chesslablab/chess-server/issues/354

**Comment by programarivm** [comment]
See:

- https://github.com/chesslablab/chess-server/issues/354

**Comment by joanhey** [comment]
It's not related, but we can improve this class.
