### ISSUE TITLE
Unit test the /ascii command

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#38]
This issue is intended to practice software architecture skills as well as unit testing.

As you may have noted, there's a one-to-one correspondence between the `Chess\Game` methods described in the [PHP Chess Docs](https://php-chess.readthedocs.io/en/latest/game-methods/) and the commands available in the chess server:

- `ascii(): string` <-> `ChessServer\Command\AsciiCommand.php`
- `captures(): array` <-> `ChessServer\Command\CapturesCommand.php`
- `castling(): ?array` <-> `ChessServer\Command\CastlingCommand.php`
- ...

All commands should be unit tested in the [`ChessServer\Tests\Unit\Command`](https://github.com/chesslablab/chess-server/tree/master/tests/unit/Command) namespace; however, the `ChessServer\Tests\Unit\Command\AsciiTest.php` file is missing at the present moment.

The missing file should be added as per the existing conventions.

Happy learning and coding!

**Comment by Pen-y-Fan** [comment]
I'm happy to take a look at this.

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/chess-server/pull/42
