### ISSUE TITLE
Update files in the ChessServer\Tests\Unit\Command namespace

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#39]
The word `Command` should be appended to all files in the [`ChessServer\Tests\Unit\Command`](https://github.com/chesslablab/chess-server/tree/master/tests/unit/Command) namespace as it is described next:

- `CapturesCommandTest.php`
- `HistoryCommandTest.php`
- `IsCheckCommandTest.php`
- ...
- `UndoMoveCommandTest.php`

**Comment by Pen-y-Fan** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/chess-server/pull/54
