### ISSUE TITLE
Only compatible with PHP 7.4, bump PHPUnit to allow PHP 8?

### ISSUE THREAD

**Issue by Pen-y-Fan** [chesslablab/chess-server#41]
I've had some problems with the setup:

- PHPUnit has a maximum PHP version of 7.4,
- rubix/ml has a minimum PHP version of 7.4, 
 
`composer install` can only be run using PHP 7.4, it will not run on PHP 8.

I'm happy to bump PHPUnit to 9.5, which will give PHP 7.4 & PHP 8. I can fix the [deprecated annotation(s) for expecting exceptions](https://github.com/sebastianbergmann/phpunit/issues/3332), is this Ok? Would you be willing to tag with Hacktoberfest?

**Comment by programarivm** [comment]
@Pen-y-Fan, welcome to ChesslabLab.

Thank you for joining the community and raising an issue. 

That's a good point. I can't wait to see what you come up with!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/chess-server/pull/43
