### ISSUE TITLE
External Auth?

### ISSUE THREAD

**Issue by tilllt** [chesslablab/chess-server#431]
Is there any external authentication method available, preferable oauth2? Or on the roadmap?

**Comment by programarivm** [comment]
Thank you @tilllt for asking this question!

JWT-based authentication is in place as per the docs.

- [/totp_signup](https://chesslablab.github.io/chess-server/totp-signup/)
- [/totp_refresh](https://chesslablab.github.io/chess-server/totp-refresh/)
- [/totp_signin](https://chesslablab.github.io/chess-server/totp-signin/)

More specifically, a rather basic TOTP authentication mechanism is implemented at the moment allowing users to sign in without a username or password.

See:

- https://github.com/Spomky-Labs/otphp/issues/230

![screencapture-chesslablab-org-en-signin-register-2024-12-12-20_57_28](https://github.com/user-attachments/assets/f144196a-a86d-4a95-b140-99278dc53a8f)
**Figure 1**. Visit the website and click on **Sign In > Register Now**

Also you may want to play around with the console and learn about the TOTP commands.

![screencapture-chesslablab-org-en-console-2024-12-12-21_00_35](https://github.com/user-attachments/assets/acfc75c5-02c6-4a63-8020-63ca4f563b5d)
**Figure 2**. Click on **Console**

Hopefully in the future Webauthn will be implemented:

- [Webauthn Demo](https://github.com/web-auth/symfony-webauthn-demo)

Keep it up,

**Comment by tilllt** [comment]
Thanks for the reply,  we are using authentik as an sso/identity Management, so i am trying to  figure out If that could be used for sign in provider, but it seems not yet, right?

I must admit that JWT is just an abbreviation i have heard before and that IT IS used in oauth2 as well....

**Comment by programarivm** [comment]
Using an authentication provider requires to store private data from users and set up a legal framework accordingly in terms of GDPR compliance, and so on and forth. ChesslaBlab is a small organization implementing basic solutions. It can be seen as a demo.
