### ISSUE TITLE
Set up a .travis.yml file to run tests on multiple PHP versions

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-server#44]
The file should be quite similar to [this one](https://github.com/chesslablab/php-chess/blob/master/.travis.yml).

**Comment by Braunson** [comment]
@programarivm What version of PHP do you want to run on? Just the travis.yml file?

**Comment by programarivm** [comment]
@Braunson, welcome to ChesslabLab.

Thank you for joining the community! 

Probably at this moment PHP 7.4 and PHP 8.0 will be okay in the `.travis.yml` file only, but it'll be nice to test more versions in a different issue perhaps. 

This way it's up to the programmer to choose the PHP version they want to run on their computers I suppose.

Please make sure to read the [Contributing Guidelines](https://medium.com/geekculture/how-to-contribute-to-chesslab-cca73fefaf70).

Keep it up, and happy learning and coding.

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/chess-server/pull/49
